name: taskflow
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  gap: ^3.0.1
  equatable: ^2.0.5
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  custom_lint: ^0.5.8
  riverpod_lint: ^2.3.7


flutter:

  uses-material-design: true
  